# Train/val/test sets as 
## 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]


#path: /content/Majasaurus/aligned/images  # dataset root dir
train: /content/Majasaurus/datasets/images/train  # train images (relative to 'path')
val: /content/Majasaurus/datasets/images/val # val images (relative to 'path')

# Classes
nc: 35  # number of classes
names: ['1s','2s','3s','4s','5s','6s','7s','8s','9s',
        '1m','2m','3m','4m','5m','6m','7m','8m','9m',
        '1p','2p','3p','4p','5p','6p','7p','8p','9p',
        'east','south','west','north','white','green','red',
        'back']  # class names